# Generated by Django 5.1.2 on 2024-11-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_producto_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado')], max_length=10),
        ),
    ]
