# Generated by Django 5.1.2 on 2024-11-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0005_producto_estado_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Motherboard', 'Motherboard'), ('RAM', 'RAM'), ('Almacenamiento', 'Almacenamiento'), ('Teclados', 'Teclados'), ('Mouses', 'Mouses'), ('Monitores', 'Monitores'), ('Sillas', 'Sillas'), ('Escritorios', 'Escritorios')], max_length=50),
        ),
    ]
