# Generated by Django 5.1.2 on 2024-11-11 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0006_alter_producto_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
