# Generated by Django 5.1.2 on 2024-11-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0009_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='promedio_calificacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
