# Generated by Django 5.1.2 on 2024-11-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0014_comentario_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosguardados',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
