# Generated by Django 5.1.2 on 2024-11-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0015_productosguardados_is_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productosguardados',
            name='is_selected',
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
