# Generated by Django 5.1.2 on 2024-11-26 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0018_remove_pedido_usuario_compra_delete_detallespago_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
