# Generated by Django 5.1.2 on 2024-11-26 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0022_compra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
