# Generated by Django 5.1.2 on 2024-11-26 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0024_compra_pagoenlinea_transferenciabancaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferenciabancaria',
            name='compra',
        ),
        migrations.DeleteModel(
            name='PagoEnLinea',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='TransferenciaBancaria',
        ),
    ]
