# Generated by Django 5.1.2 on 2024-11-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0028_remove_detalleventa_is_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='calificacion',
            field=models.IntegerField(blank=True, choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], null=True),
        ),
    ]
