# Generated by Django 5.1.2 on 2024-11-26 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0029_comentario_calificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='calificacion',
        ),
        migrations.DeleteModel(
            name='Calificacion',
        ),
    ]
