# Generated by Django 5.1.2 on 2024-11-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0030_remove_comentario_calificacion_delete_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
