# Generated by Django 5.1.2 on 2024-12-02 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0032_detalleventa_is_selected_detalleventa_precio_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, 'La calificación mínima es 1'), django.core.validators.MaxValueValidator(5, 'La calificación máxima es 5')]),
        ),
    ]
